format: "xrdf"

format_version: 1.0

default_joint_positions:
  rh_FFJ4: 0.0
  rh_FFJ3: 0.0
  rh_FFJ2: 0.0
  rh_FFJ1: 0.0
  rh_MFJ4: 0.0
  rh_MFJ3: 0.0
  rh_MFJ2: 0.0
  rh_MFJ1: 0.0
  rh_RFJ4: 0.0
  rh_RFJ3: 0.0
  rh_RFJ2: 0.0
  rh_RFJ1: 0.0
  rh_LFJ5: 0.0
  rh_LFJ4: 0.0
  rh_LFJ3: 0.0
  rh_LFJ2: 0.0
  rh_LFJ1: 0.0
  rh_THJ5: 0.0
  rh_THJ4: 0.0
  rh_THJ3: 0.0
  rh_THJ2: 0.0
  rh_THJ1: 0.0

cspace:
  joint_names:
    - "rh_FFJ4"
    - "rh_FFJ3"
    - "rh_FFJ2"
    - "rh_FFJ1"
    - "rh_MFJ4"
    - "rh_MFJ3"
    - "rh_MFJ2"
    - "rh_MFJ1"
    - "rh_RFJ4"
    - "rh_RFJ3"
    - "rh_RFJ2"
    - "rh_RFJ1"
    - "rh_LFJ5"
    - "rh_LFJ4"
    - "rh_LFJ3"
    - "rh_LFJ2"
    - "rh_LFJ1"
    - "rh_THJ5"
    - "rh_THJ4"
    - "rh_THJ3"
    - "rh_THJ2"
    - "rh_THJ1"
  acceleration_limits: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
  jerk_limits: [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]

collision:
  geometry: "auto_generated_collision_sphere_group"

self_collision:
  geometry: "auto_generated_collision_sphere_group"
  ignore:
    rh_palm:
      - "rh_ffproximal"
      - "rh_mfproximal"
      - "rh_rfproximal"
      - "rh_lfmetacarpal"
      - "rh_thproximal"
    rh_ffproximal:
      - "rh_ffmiddle"
    rh_ffmiddle:
      - "rh_ffdistal"
    rh_ffdistal: []
    rh_mfproximal:
      - "rh_mfmiddle"
    rh_mfmiddle:
      - "rh_mfdistal"
    rh_mfdistal: []
    rh_rfproximal:
      - "rh_rfmiddle"
    rh_rfmiddle:
      - "rh_rfdistal"
    rh_rfdistal: []
    rh_thproximal:
      - "rh_thmiddle"
    rh_thmiddle:
      - "rh_thdistal"
    rh_thdistal: []
    rh_lfmetacarpal:
      - "rh_lfproximal"
    rh_lfproximal:
      - "rh_lfmiddle"
    rh_lfmiddle:
      - "rh_lfdistal"
    rh_lfdistal: []

geometry:
  auto_generated_collision_sphere_group:
    spheres:
      rh_palm:
        - center: [0.025, -0.005, 0.015]
          radius: 0.02
        - center: [0.028, 0.0, 0.054]
          radius: 0.0125
        - center: [-0.02, -0.003, 0.015]
          radius: 0.02
        - center: [0.029, 0.0, 0.074]
          radius: 0.0125
        - center: [-0.01, 0.0, 0.074]
          radius: 0.0125
        - center: [-0.01, 0.0, 0.053]
          radius: 0.0125
        - center: [0.009, 0.0, 0.053]
          radius: 0.0125
        - center: [0.01, 0.0, 0.077]
          radius: 0.0125
        - center: [0.001, 0.0, 0.029]
          radius: 0.02
      rh_ffproximal:
        - center: [0.0, 0.0, 0.0]
          radius: 0.01
        - center: [0.0, 0.0, 0.034]
          radius: 0.009
        - center: [0.0, 0.0, 0.017]
          radius: 0.0095
      rh_ffmiddle:
        - center: [0.0, 0.0, 0.002]
          radius: 0.009
        - center: [0.0, 0.0, 0.016]
          radius: 0.009
      rh_ffdistal:
        - center: [0.0, 0.0, 0.001]
          radius: 0.008
        - center: [0.0, 0.001, 0.012]
          radius: 0.008
        - center: [0.0, 0.001, 0.022]
          radius: 0.0075
      rh_mfproximal:
        - center: [0.0, 0.0, 0.0]
          radius: 0.01
        - center: [0.0, 0.0, 0.034]
          radius: 0.009
        - center: [0.0, 0.0, 0.017]
          radius: 0.0095
      rh_mfmiddle:
        - center: [0.0, 0.0, 0.002]
          radius: 0.009
        - center: [0.0, 0.0, 0.016]
          radius: 0.009
      rh_mfdistal:
        - center: [0.0, 0.0, 0.001]
          radius: 0.008
        - center: [0.0, 0.001, 0.012]
          radius: 0.008
        - center: [0.0, 0.001, 0.022]
          radius: 0.0075
      rh_rfproximal:
        - center: [0.0, 0.0, 0.0]
          radius: 0.01
        - center: [0.0, 0.0, 0.034]
          radius: 0.009
        - center: [0.0, 0.0, 0.017]
          radius: 0.0095
      rh_rfmiddle:
        - center: [0.0, 0.0, 0.002]
          radius: 0.009
        - center: [0.0, 0.0, 0.016]
          radius: 0.009
      rh_rfdistal:
        - center: [0.0, 0.0, 0.001]
          radius: 0.008
        - center: [0.0, 0.001, 0.012]
          radius: 0.008
        - center: [0.0, 0.001, 0.022]
          radius: 0.0075
      rh_lfmetacarpal:
        - center: [-0.025, 0.0, 0.038]
          radius: 0.012
        - center: [-0.012, 0.0, 0.019]
          radius: 0.012
      rh_lfproximal:
        - center: [0.0, 0.0, 0.0]
          radius: 0.01
        - center: [0.0, 0.0, 0.034]
          radius: 0.009
        - center: [0.0, 0.0, 0.017]
          radius: 0.0095
      rh_lfmiddle:
        - center: [0.0, 0.0, 0.002]
          radius: 0.009
        - center: [0.0, 0.0, 0.016]
          radius: 0.009
      rh_lfdistal:
        - center: [0.0, 0.0, 0.001]
          radius: 0.008
        - center: [0.0, 0.001, 0.012]
          radius: 0.008
        - center: [0.0, 0.001, 0.022]
          radius: 0.0075
      rh_thproximal:
        - center: [0.0, -0.002, 0.005]
          radius: 0.012
        - center: [0.0, 0.0, 0.037]
          radius: 0.012
        - center: [0.0, -0.001, 0.021]
          radius: 0.012
      rh_thmiddle:
        - center: [0.001, 0.0, 0.012]
          radius: 0.01
        - center: [0.001, 0.0, 0.028]
          radius: 0.01
      rh_thdistal:
        - center: [0.0, 0.001, 0.015]
          radius: 0.01
        - center: [0.0, 0.002, 0.027]
          radius: 0.008
